export const QUEST_REWARD_CHANCE = 0.5;

export const CRAFT_CATEGORIES = {
    weapon:    { en: 'Weapons',     ru: 'Оружие',        de: 'Waffen' },
    armor:     { en: 'Armor',       ru: 'Броня',         de: 'Rüstung' },
    accessory: { en: 'Accessories', ru: 'Аксессуары',    de: 'Accessoires' },
    potion:    { en: 'Potions',     ru: 'Зелья',         de: 'Tränke' }
};

export const CRAFTING_RECIPES = [
    {
        id: 'craft_wooden_staff',
        name: 'Wooden Staff',
        nameRu: 'Деревянный Посох',
        nameDe: 'Holzstab',
        category: 'weapon',
        rarity: 'common',
        slot: 'weapon',
        levelRequired: 0,
        materials: { wood: 3, leaf: 1 },
        stats: { dmg: 4 },
        texKey: 'item_stick',
        description: 'A simple staff carved from forest wood.',
        descriptionRu: 'Простой посох, вырезанный из лесного дерева.',
        descriptionDe: 'Ein einfacher Stab aus Waldholz geschnitzt.'
    },
    {
        id: 'craft_leather_cap',
        name: 'Leather Cap',
        nameRu: 'Кожаная Шапка',
        nameDe: 'Lederkappe',
        category: 'armor',
        rarity: 'common',
        slot: 'armor',
        levelRequired: 0,
        materials: { wood: 2, stone: 1 },
        stats: { hp: 10 },
        texKey: 'item_leather',
        description: 'Light headgear reinforced with stone.',
        descriptionRu: 'Лёгкий головной убор, укреплённый камнем.',
        descriptionDe: 'Leichter Kopfschutz, mit Stein verstärkt.'
    },
    {
        id: 'craft_herb_pendant',
        name: 'Herb Pendant',
        nameRu: 'Травяной Кулон',
        nameDe: 'Krautanhänger',
        category: 'accessory',
        rarity: 'common',
        slot: 'accessory',
        levelRequired: 0,
        materials: { leaf: 2, mushroom: 1 },
        stats: { hp: 5, regen: 1 },
        texKey: 'item_herb',
        description: 'A pendant imbued with herbal essence. Promotes natural healing.',
        descriptionRu: 'Кулон, пропитанный травяной эссенцией. Способствует естественному исцелению.',
        descriptionDe: 'Ein mit Krautessenz getränkter Anhänger. Fördert natürliche Heilung.'
    },
    {
        id: 'craft_stone_blade',
        name: 'Stone Blade',
        nameRu: 'Каменный Клинок',
        nameDe: 'Steinklinge',
        category: 'weapon',
        rarity: 'uncommon',
        slot: 'weapon',
        levelRequired: 1,
        materials: { stone: 4, wood: 2 },
        stats: { dmg: 7, crit: 1 },
        texKey: 'item_stone',
        description: 'A blade sharpened from river stone. Brittle but sharp.',
        descriptionRu: 'Клинок, заточенный из речного камня. Хрупкий, но острый.',
        descriptionDe: 'Eine aus Flussstein geschliffene Klinge. Spröde, aber scharf.'
    },
    {
        id: 'craft_mushroom_cap',
        name: 'Mushroom Helm',
        nameRu: 'Грибной Шлем',
        nameDe: 'Pilzhelm',
        category: 'armor',
        rarity: 'uncommon',
        slot: 'armor',
        levelRequired: 1,
        materials: { mushroom: 3, wood: 2 },
        stats: { hp: 18, regen: 1 },
        texKey: 'item_mush',
        description: 'A helmet grown from enchanted mushroom cap. Surprisingly durable.',
        descriptionRu: 'Шлем, выращенный из зачарованной шляпки гриба. Удивительно прочный.',
        descriptionDe: 'Ein Helm aus verzaubertem Pilz gewachsen. Überraschend haltbar.'
    },
    {
        id: 'craft_healing_salve',
        name: 'Healing Salve',
        nameRu: 'Целебная Мазь',
        nameDe: 'Heilsalbe',
        category: 'potion',
        rarity: 'uncommon',
        slot: 'accessory',
        levelRequired: 1,
        materials: { mushroom: 2, herb: 1 },
        stats: { hp: 12, regen: 2 },
        texKey: 'item_mush',
        description: 'A thick salve that accelerates natural recovery.',
        descriptionRu: 'Густая мазь, ускоряющая естественное восстановление.',
        descriptionDe: 'Eine dicke Salbe, die die natürliche Erholung beschleunigt.'
    },
    {
        id: 'craft_arcane_wand',
        name: 'Arcane Wand',
        nameRu: 'Тайный Жезл',
        nameDe: 'Arkaner Zauberstab',
        category: 'weapon',
        rarity: 'rare',
        slot: 'weapon',
        levelRequired: 2,
        materials: { wood: 5, herb: 3, gem_shard: 2 },
        stats: { dmg: 12, crit: 3 },
        texKey: 'item_ruby',
        description: 'A wand channeling raw arcane energy through gem shards.',
        descriptionRu: 'Жезл, направляющий чистую магическую энергию через осколки самоцветов.',
        descriptionDe: 'Ein Zauberstab, der rohe Arkane Energie durch Edelsteinbrocken lenkt.'
    },
    {
        id: 'craft_gemstone_ring',
        name: 'Gemstone Ring',
        nameRu: 'Самоцветное Кольцо',
        nameDe: 'Edelsteinring',
        category: 'accessory',
        rarity: 'rare',
        slot: 'accessory',
        levelRequired: 2,
        materials: { gem_shard: 3, herb: 2 },
        stats: { hp: 15, dmg: 8 },
        texKey: 'item_sapph',
        description: 'A ring set with a luminous gem shard. Amplifies inner power.',
        descriptionRu: 'Кольцо с светящимся осколком самоцвета. Усиливает внутреннюю силу.',
        descriptionDe: 'Ein Ring mit einem leuchtenden Edelsteinbrocken. Verstärkt die innere Kraft.'
    },
    {
        id: 'craft_iron_potion',
        name: 'Iron Elixir',
        nameRu: 'Железный Эликсир',
        nameDe: 'Eisenelixier',
        category: 'potion',
        rarity: 'rare',
        slot: 'accessory',
        levelRequired: 2,
        materials: { stone: 5, herb: 3, mushroom: 2 },
        stats: { hp: 25, dmg: 5 },
        texKey: 'item_stone',
        description: 'An elixir that hardens the body like iron.',
        descriptionRu: 'Эликсир, отвердевающий тело как железо.',
        descriptionDe: 'Ein Elixier, das den Körper härter wie Eisen macht.'
    },
    {
        id: 'craft_flame_staff',
        name: 'Flame-Touched Staff',
        nameRu: 'Огненный Посох',
        nameDe: 'Flammenberührter Stab',
        category: 'weapon',
        rarity: 'epic',
        slot: 'weapon',
        levelRequired: 3,
        materials: { wood: 8, herb: 4, gem_shard: 3 },
        stats: { dmg: 18, crit: 5, spellPercent: 3 },
        texKey: 'item_flame',
        description: 'A staff infused with elemental fire. Burns on contact.',
        descriptionRu: 'Посох, пропитанный стихийным огнём. Горит при контакте.',
        descriptionDe: 'Ein mit elementarem Feuer durchdrungener Stab. Brennt bei Kontakt.'
    },
    {
        id: 'craft_shadow_cloak',
        name: 'Shadow Cloak',
        nameRu: 'Плащ Теней',
        nameDe: 'Schattenumhang',
        category: 'armor',
        rarity: 'epic',
        slot: 'armor',
        levelRequired: 3,
        materials: { herb: 5, mushroom: 4, gem_shard: 2 },
        stats: { hp: 30, dodgePercent: 3 },
        texKey: 'acc_mantle',
        description: 'A cloak woven from shadow-thread. Makes the wearer harder to hit.',
        descriptionRu: 'Плащ, сотканный из теневой нити. Делает носящего труднее для попадания.',
        descriptionDe: 'Ein aus Schattengewebe gewebter Umhang. Macht den Träger schwerer zu treffen.'
    },
    {
        id: 'craft_soul_pendant',
        name: 'Soul Pendant',
        nameRu: 'Душевный Кулон',
        nameDe: 'Seelenanhänger',
        category: 'accessory',
        rarity: 'epic',
        slot: 'accessory',
        levelRequired: 3,
        materials: { gem_shard: 4, herb: 3 },
        stats: { hp: 20, dmg: 10, regenPercent: 2 },
        texKey: 'acc_amulet',
        description: 'A pendant resonating with soul energy. Enhances life force.',
        descriptionRu: 'Кулон, резонирующий с энергией души. Усиливает жизненную силу.',
        descriptionDe: 'Ein Anhänger, der mit Seelenenergie resoniert. Verstärkt die Lebenskraft.'
    },
    {
        id: 'craft_eternity_staff',
        name: 'Staff of Eternity',
        nameRu: 'Посох Вечности',
        nameDe: 'Stab der Ewigkeit',
        category: 'weapon',
        rarity: 'legendary',
        slot: 'weapon',
        levelRequired: 4,
        materials: { wood: 10, herb: 8, gem_shard: 5 },
        stats: { dmg: 25, crit: 8, spellPercent: 5 },
        texKey: 'acc_book',
        description: 'A legendary staff that has endured for ages. Its power is immense.',
        descriptionRu: 'Легендарный посох, простоявший веками. Его сила огромна.',
        descriptionDe: 'Ein legendärer Stab, der Jahrhaltende überdauert hat. Seine Kraft ist gewaltig.'
    },
    {
        id: 'craft_dragon_plate',
        name: 'Dragon Plate',
        nameRu: 'Драконий Доспех',
        nameDe: 'Drachenplatte',
        category: 'armor',
        rarity: 'legendary',
        slot: 'armor',
        levelRequired: 4,
        materials: { stone: 10, gem_shard: 5, herb: 3 },
        stats: { hp: 60, dmg: 10, damageReduction: 3 },
        texKey: 'item_dscale',
        description: 'Armor forged from the hardest materials. Nearly indestructible.',
        descriptionRu: 'Доспех, выкованный из самых прочных материалов. Почти неуничтожимый.',
        descriptionDe: 'Aus den härtesten Materialien geschmiedete Rüstung. Fast unzerstörbar.'
    },
    {
        id: 'craft_life_ring',
        name: 'Ring of Vitality',
        nameRu: 'Кольцо Жизненной Силы',
        nameDe: 'Ring der Vitalität',
        category: 'accessory',
        rarity: 'legendary',
        slot: 'accessory',
        levelRequired: 4,
        materials: { gem_shard: 6, mushroom: 5, herb: 4 },
        stats: { hp: 40, regenPercent: 5, dmg: 8 },
        texKey: 'item_crown',
        description: 'A ring pulsing with pure life energy. The wearer barely needs rest.',
        descriptionRu: 'Кольцо, пульсирующее чистой жизненной энергией. Носящий почти не нуждается в отдыхе.',
        descriptionDe: 'Ein Ring, der rein pulsiert mit Lebensenergie. Der Träger braucht kaum noch Ruhe.'
    },
    {
        id: 'craft_void_scepter',
        name: 'Void Scepter',
        nameRu: 'Скипетр Пустоты',
        nameDe: 'Szepter der Leere',
        category: 'weapon',
        rarity: 'legendary',
        slot: 'weapon',
        levelRequired: 5,
        materials: { wood: 15, gem_shard: 10, herb: 8 },
        stats: { dmg: 35, crit: 10, spellPercent: 8 },
        texKey: 'acc_book',
        description: 'A scepter forged in the space between worlds. Reality bends to its will.',
        descriptionRu: 'Скипетр, выкованный в пространстве между мирами. Реальность подчиняется его воле.',
        descriptionDe: 'Ein Szepter, geschmieden im Raum zwischen Welten. Realität beugt sich seinem Willen.'
    },
    {
        id: 'craft_purestone_amulet',
        name: 'Purestone Amulet',
        nameRu: 'Амулет Чистого Камня',
        nameDe: 'Reinsteinedelstein-Amulett',
        category: 'accessory',
        rarity: 'legendary',
        slot: 'accessory',
        levelRequired: 5,
        materials: { gem_shard: 12, mushroom: 6, herb: 6 },
        stats: { hp: 50, dmg: 15, regenPercent: 5, critPercent: 3 },
        texKey: 'acc_amulet',
        description: 'An amulet containing a perfectly formed gem shard. Radiates purity.',
        descriptionRu: 'Амулет, содержащий идеально сформированный осколок самоцвета. Излучает чистоту.',
        descriptionDe: 'Ein Amulett mit einem perfekt geformten Edelsteinbrocken. Strahlt Reinheit aus.'
    }
];
