// Difficulty
export { DIFFICULTIES, DIFF_NAMES, DIFF_MULT } from './difficulty.js';

// Rarity
export { RARITY_COLORS, RARITY_NAMES } from './rarity.js';

// Enemies & Bosses
export {
    ENEMY_TYPES, ENEMY_COUNT, EQUIP_DROP_CHANCE, BOSS_DROP_CHANCE, ACCOUNT_EQUIP_DROP_CHANCE,
    BOSS_TYPE, MINE_ENEMY_TYPES, MINE_ENEMY_COUNT, MINE_EQUIP_DROP_CHANCE, MINE_BOSS_TYPE,
    CAVE_ENEMY_TYPES, CAVE_ENEMY_COUNT, CAVE_EQUIP_DROP_CHANCE, CAVE_BOSS_TYPE, CAVE_SMALL_BAT, CAVE_BOSS_EXP,
    VILLAGE_CAMP_COUNT, VILLAGE_MOBS_PER_CAMP, VILLAGE_ENEMY_TYPES, VILLAGE_BOSS_TYPE, VILLAGE_CORPSE_MINION,
    HELL_CAMP_COUNT, HELL_MOBS_PER_CAMP, HELL_ENEMY_TYPES, HELL_BOSS_TYPE, HELL_BOSS_MINION,
    SNOWY_VILLAGE_ENEMY_TYPES, SNOWY_VILLAGE_BOSS_TYPE, SNOWY_BOSS_MINION,
    BANDIT_TYPES, BANDIT_LEADER_BOSS, CASTLE_CHEST_COUNT, CASTLE_CHEST_DROP_CHANCE,
    BESTIARY_LEVELS, BESTIARY_DIFF_MULT, BESTIARY_ENEMIES
} from './enemies.js';

// Items
export {
    MATERIAL_DB, CAVE_MATERIALS, VILLAGE_MATERIALS,
    EQUIP_DB, ACCOUNT_EQUIP_DB, ACCOUNT_EQUIP_DB_CAVE, CAVE_RELIC_CLASSES,
    ACCOUNT_EQUIP_DB_VILLAGE, VILLAGE_CHEST_DROP_ITEMS,
    SECRET_KEY_ITEM, MAGMA_ARMOR, HEAT_CRYSTAL, WARMTH_CORE, CASTLE_KEY,
    MATERIAL_BOOK_LEVELS, MATERIAL_BOOK_ENTRIES
} from './items.js';

// Zones
export {
    GAME_WIDTH, GAME_HEIGHT,
    FOREST_HEIGHT, STUMP_COUNT, PORTAL_POS, PORTAL_ENTER_DIST, ARENA_EXIT_POS, FOREST_RETURN_POS,
    CORRUPTION, MATERIAL_SLOTS, EQUIP_BAG_SLOTS, ACCOUNT_EQUIP_SLOTS, ACCOUNT_EQUIP_BAG_SLOTS, EMPTY_ACCOUNT_EQUIPMENT,
    MINE_ROCK_COUNT, MINE_CRYSTAL_COUNT, MINE_EXIT_POS, MINE_RETURN_POS, MINE_BOSS_PORTAL_POS,
    MINE_CHEST_COUNT, MINE_CHEST_DROP_CHANCE,
    CAVE_WIDTH, CAVE_HEIGHT, CAVE_CHEST_COUNT, CAVE_CHEST_DROP_CHANCE,
    CAVE_CHEST_OPEN_KEY, CAVE_CHEST_CLOSED_KEY, CAVE_CHEST_W, CAVE_CHEST_H,
    MEADOW_POS, MEADOW_GATE_POS, MEADOW_WIDTH, MEADOW_HEIGHT,
    VILLAGE_WIDTH, VILLAGE_HEIGHT, CEMETERY_HEIGHT, VILLAGE_TOTAL_HEIGHT,
    VILLAGE_CAMP_POSITIONS, VILLAGE_HOUSE_POSITIONS, VILLAGE_CHILD_HOUSE,
    VILLAGE_CORPSE_POSITIONS, VILLAGE_GARDEN_POSITIONS,
    VILLAGE_CHEST_COUNT_MIN, VILLAGE_CHEST_COUNT_MAX, VILLAGE_CHEST_DROP_CHANCE,
    VILLAGE_CHEST_EQUIP_DROP_CHANCE, VILLAGE_CHEST_OPEN_KEY, VILLAGE_CHEST_CLOSED_KEY,
    VILLAGE_CHEST_W, VILLAGE_CHEST_H,
    HELL_WIDTH, HELL_HEIGHT, HELL_LAVA_DAMAGE, HELL_LAVA_INTERVAL, HELL_HEAT_DAMAGE,
    HELL_CAMP_POSITIONS, HELL_LAVA_POSITIONS, HELL_CHEST_COUNT, HELL_CHEST_DROP_CHANCE,
    CASTLE_WIDTH, CASTLE_ROOM_HEIGHT, CASTLE_TOTAL_HEIGHT, CASTLE_ROOMS, CASTLE_ATTIC_INDEX,
    CASTLE_CHEST_POSITIONS, CASTLE_VILLAGER_POSITIONS, CASTLE_SPAWN_POS,
    SNOWY_VILLAGE_CAMP_POSITIONS, SNOWY_VILLAGE_CHEST_COUNT, SNOWY_VILLAGE_CHEST_DROP_CHANCE
} from './zones.js';

// Spells
export { SPELLS } from './spells.js';

// Crafting
export { QUEST_REWARD_CHANCE, CRAFT_CATEGORIES, CRAFTING_RECIPES } from './crafting.js';

// Quests & NPCs
export { NPC_DB, QUEST_DB, CART_DRIVER_NPC } from './quests.js';

// Soul Book
export { SOUL_BOOK_LEVELS, SOUL_BOOK_ENTRIES } from './enemies.js';
