// Difficulty
export { DIFFICULTIES, DIFF_NAMES, DIFF_MULT, DIFF_COLORS, DIFF_TEXT_COLORS } from './difficulty.js';

// Rarity
export { RARITY_COLORS, RARITY_NAMES } from './rarity.js';

// Enemies & Bosses
export {
    ENEMY_TYPES, ENEMY_COUNT, EQUIP_DROP_CHANCE, BOSS_DROP_CHANCE, ACCOUNT_EQUIP_DROP_CHANCE,
    BOSS_TYPE, MINE_ENEMY_TYPES, MINE_ENEMY_COUNT, MINE_EQUIP_DROP_CHANCE, MINE_BOSS_TYPE,
    CAVE_ENEMY_TYPES, CAVE_ENEMY_COUNT, CAVE_EQUIP_DROP_CHANCE, CAVE_BOSS_TYPE, CAVE_SMALL_BAT, CAVE_BOSS_EXP,
    VILLAGE_CAMP_COUNT, VILLAGE_MOBS_PER_CAMP, VILLAGE_ENEMY_TYPES, VILLAGE_BOSS_TYPE, VILLAGE_CORPSE_MINION,
    HELL_CAMP_COUNT, HELL_MOBS_PER_CAMP, HELL_ENEMY_TYPES, HELL_BOSS_TYPE, HELL_BOSS_MINION,
    SNOWY_VILLAGE_ENEMY_TYPES, SNOWY_VILLAGE_BOSS_TYPE, SNOWY_BOSS_MINION,
    BANDIT_TYPES, BANDIT_LEADER_BOSS, CASTLE_CHEST_COUNT, CASTLE_CHEST_DROP_CHANCE,
    DEPTHS_CAMP_COUNT, DEPTHS_MOBS_PER_CAMP, DEPTHS_ENEMY_TYPES, DEPTHS_BOSS_TYPE, DEPTHS_BOSS_MINION,
    CURSED_CAMP_COUNT, CURSED_MOBS_PER_CAMP, CURSED_ENEMY_TYPES, CURSED_BOSS_TYPE, CURSED_BOSS_MINION,
    SHADOW_CAMP_COUNT, SHADOW_MOBS_PER_CAMP, SHADOW_ENEMY_TYPES, SHADOW_BOSS_TYPE, SHADOW_BOSS_MINION,
    TOWER_CAMP_COUNT, TOWER_MOBS_PER_CAMP, TOWER_ENEMY_TYPES, TOWER_BOSS_TYPE, TOWER_BOSS_MINION,
    THRONE_BOSS_TYPE, THRONE_BOSS_MINION_TANK, THRONE_BOSS_MINION_MAGE, THRONE_BOSS_MINION_ASSASSIN,
    BESTIARY_LEVELS, BESTIARY_DIFF_MULT, BESTIARY_ENEMIES
} from './enemies.js';

// Items
export {
    MATERIAL_DB, CAVE_MATERIALS, VILLAGE_MATERIALS, DEPTHS_MATERIALS,
    EQUIP_DB, ACCOUNT_EQUIP_DB, ACCOUNT_EQUIP_DB_CAVE, CAVE_RELIC_CLASSES,
    ACCOUNT_EQUIP_DB_VILLAGE, ACCOUNT_EQUIP_DB_DEPTHS, DEPTHS_RELIC_CLASSES,
    ACCOUNT_EQUIP_DB_CURSED, CURSED_RELIC_CLASSES,
    ACCOUNT_EQUIP_DB_SHADOW, SHADOW_RELIC_CLASSES,
    ACCOUNT_EQUIP_DB_TOWER, TOWER_RELIC_CLASSES,
    ACCOUNT_EQUIP_DB_THRONE, THRONE_RELIC_CLASSES,
    VILLAGE_CHEST_DROP_ITEMS, DEPTHS_CHEST_DROP_ITEMS, CURSED_CHEST_DROP_ITEMS, SHADOW_CHEST_DROP_ITEMS, TOWER_CHEST_DROP_ITEMS,
    SECRET_KEY_ITEM, MAGMA_ARMOR, HEAT_CRYSTAL, WARMTH_CORE, CASTLE_KEY,
    MATERIAL_BOOK_LEVELS, MATERIAL_BOOK_ENTRIES
} from './items.js';

// Zones
export {
    GAME_WIDTH, GAME_HEIGHT,
    FOREST_HEIGHT, STUMP_COUNT, PORTAL_POS, PORTAL_ENTER_DIST, ARENA_EXIT_POS, FOREST_RETURN_POS,
    CORRUPTION, MATERIAL_SLOTS, EQUIP_BAG_SLOTS, ACCOUNT_EQUIP_SLOTS, ACCOUNT_EQUIP_BAG_SLOTS, EMPTY_ACCOUNT_EQUIPMENT,
    MINE_ROCK_COUNT, MINE_CRYSTAL_COUNT, MINE_EXIT_POS, MINE_RETURN_POS, MINE_BOSS_PORTAL_POS,
    MINE_CHEST_COUNT, MINE_CHEST_DROP_CHANCE,
    CAVE_WIDTH, CAVE_HEIGHT, CAVE_CHEST_COUNT, CAVE_CHEST_DROP_CHANCE,
    CAVE_CHEST_OPEN_KEY, CAVE_CHEST_CLOSED_KEY, CAVE_CHEST_W, CAVE_CHEST_H,
    MEADOW_POS, MEADOW_GATE_POS, MEADOW_WIDTH, MEADOW_HEIGHT,
    VILLAGE_WIDTH, VILLAGE_HEIGHT, CEMETERY_HEIGHT, VILLAGE_TOTAL_HEIGHT,
    VILLAGE_CAMP_POSITIONS, VILLAGE_HOUSE_POSITIONS, VILLAGE_CHILD_HOUSE,
    VILLAGE_CORPSE_POSITIONS, VILLAGE_GARDEN_POSITIONS,
    VILLAGE_CHEST_COUNT_MIN, VILLAGE_CHEST_COUNT_MAX, VILLAGE_CHEST_DROP_CHANCE,
    VILLAGE_CHEST_EQUIP_DROP_CHANCE, VILLAGE_CHEST_OPEN_KEY, VILLAGE_CHEST_CLOSED_KEY,
    VILLAGE_CHEST_W, VILLAGE_CHEST_H,
    HELL_WIDTH, HELL_HEIGHT, HELL_LAVA_DAMAGE, HELL_LAVA_INTERVAL, HELL_HEAT_DAMAGE,
    HELL_CAMP_POSITIONS, HELL_LAVA_POSITIONS, HELL_CHEST_COUNT, HELL_CHEST_DROP_CHANCE,
    CASTLE_WIDTH, CASTLE_ROOM_HEIGHT, CASTLE_TOTAL_HEIGHT, CASTLE_ROOMS, CASTLE_ATTIC_INDEX,
    CASTLE_CHEST_POSITIONS, CASTLE_VILLAGER_POSITIONS, CASTLE_SPAWN_POS,
    SNOWY_VILLAGE_CAMP_POSITIONS, SNOWY_VILLAGE_CHEST_COUNT, SNOWY_VILLAGE_CHEST_DROP_CHANCE,
    DEPTHS_WIDTH, DEPTHS_HEIGHT, DEPTHS_FLOOR_HEIGHT, DEPTHS_CAMP_POSITIONS,
    DEPTHS_CHEST_POSITIONS, DEPTHS_PORTAL_POSITIONS, DEPTHS_BOSS_POSITION,
    DEPTHS_CHEST_COUNT, DEPTHS_CHEST_DROP_CHANCE,
    CURSED_WIDTH, CURSED_HEIGHT, CURSED_ZONE_HEIGHT, CURSED_CAMP_POSITIONS,
    CURSED_CHEST_POSITIONS, CURSED_PORTAL_POSITIONS, CURSED_BOSS_POSITION,
    CURSED_CHEST_COUNT, CURSED_CHEST_DROP_CHANCE,
    SHADOW_WIDTH, SHADOW_HEIGHT, SHADOW_FLOOR_HEIGHT, SHADOW_CAMP_POSITIONS,
    SHADOW_CHEST_POSITIONS, SHADOW_PORTAL_POSITIONS, SHADOW_BOSS_POSITION,
    SHADOW_CHEST_COUNT, SHADOW_CHEST_DROP_CHANCE,
    TOWER_WIDTH, TOWER_HEIGHT, TOWER_ROOM_HEIGHT, TOWER_ROOMS, TOWER_CAMP_POSITIONS,
    TOWER_CHEST_POSITIONS, TOWER_STAIR_POSITIONS, TOWER_BOSS_POSITION,
    TOWER_CHEST_COUNT, TOWER_CHEST_DROP_CHANCE,
    THRONE_WIDTH, THRONE_HEIGHT, THRONE_BOSS_POSITION
} from './zones.js';

// Spells
export { SPELLS } from './spells.js';

// Crafting
export { QUEST_REWARD_CHANCE, CRAFT_CATEGORIES, CRAFTING_RECIPES } from './crafting.js';

// Gold & Shop
export { GOLD_DROPS, rollGold, rollBossGold, rollChestGold, CONSUMABLES, SHOP_MATERIALS, SHOP_EQUIP_RARITY_CHANCE, SHOP_EQUIP_PRICES, SELL_PRICE_RATIO } from './gold.js';

// Quests & NPCs
export { NPC_DB, QUEST_DB, CART_DRIVER_NPC } from './quests.js';

// Soul Book
export { SOUL_BOOK_LEVELS, SOUL_BOOK_ENTRIES } from './enemies.js';

// Balance (combat, spells, player tuning)
export {
    INVINCIBILITY_DURATION, MELEE_RANGE, MELEE_COOLDOWN, MELEE_DMG_MULT, MELEE_HIT_RADIUS,
    MELEE_SLASH_COLOR, RANGED_PROJECTILE_SPEED, RANGED_ATTACK_RANGE,
    MAX_ARMOR_SHRED_STACKS, ARMOR_SHRED_PER_STACK_PCT,
    LOW_HP_DAMAGE_BONUS_THRESHOLD, ARMOR_SHRED_DAMAGE_BONUS_PER_STACK, LIFELINK_DAMAGE_REDUCTION,
    CHEST_RESPAWN_MS, STUMP_RESPAWN_MS, ENEMY_RESPAWN_MS, VILLAGE_CHEST_DESTROY_DELAY,
    COIN_DROP_COUNT, COIN_SPREAD_X, COIN_SPREAD_Y, COIN_FLOAT_DISTANCE,
    BOSS_SECOND_DROP_CHANCE_FOREST, BOSS_SECOND_DROP_CHANCE_MINE, BOSS_SECOND_DROP_CHANCE_CAVE,
    ENEMY_DROP_MATERIAL_COUNT, CHEST_DROP_MATERIAL_COUNT,
    DAMAGE_SHAKE_DURATION, DAMAGE_SHAKE_INTENSITY, RESPAWN_SHAKE_DURATION, RESPAWN_SHAKE_INTENSITY,
    BOSS_DEATH_SHAKE_DURATION, BOSS_DEATH_SHAKE_INTENSITY,
    PROJECTILE_DMG_SCALING, METEOR_DMG_SCALING, ACID_FLASK_DMG_SCALING,
    SHIELD_HP_BONUS_PCT, CHAIN_LIGHTNING_DAMAGE_MULT, DOT_TICK_INTERVAL,
    METEOR_CAST_RANGE, METEOR_RADIUS, CHEMICAL_CLOUD_CAST_RANGE, CHEMICAL_CLOUD_RADIUS,
    ACID_FLASK_CAST_RANGE, ACID_FLASK_RADIUS, HOLY_NOVA_RADIUS,
    TOXIC_PUDDLE_CAST_RANGE, TOXIC_PUDDLE_RADIUS, TOXIC_PUDDLE_SLOW_PCT,
    HEAL_ZONE_RADIUS, HEAL_ZONE_DURATION, HEAL_ZONE_HEAL_PER_SEC,
    SOUL_STRIKE_HEAL_ON_HIT_PCT, PURIFY_HEAL_MULT,
    BASE_CRIT_DAMAGE_MULT, DEFAULT_CORRUPTION_DECAY,
    LEVEL_UP_XP_BASE, LEVEL_UP_XP_EXPONENT,
    UPGRADE_HP_PER_LVL, UPGRADE_DMG_PER_LVL, UPGRADE_SPD_PER_LVL, UPGRADE_CRIT_PER_LVL, UPGRADE_REGEN_PER_LVL,
    CONSUMABLE_DURATION_MS, CONSUMABLE_LIFESTEAL_DURATION_MS,
    RARITY_XP_MULT, ITEM_DELETE_XP_BASE, ITEM_DELETE_XP_LEVEL_SCALE, ACCOUNT_XP_FRACTION,
    ENEMY_WANDER_SPEED, BOSS_CLONE_BASE_SPEED, BOSS_CLONE_CLOSE_RANGE_SPEED_MULT,
    PLAYER_BODY_WIDTH, PLAYER_BODY_HEIGHT, PLAYER_BODY_OFFSET_X, PLAYER_BODY_OFFSET_Y,
    AUTO_SAVE_INTERVAL, BOSS_DEFEATED_TEXT_DURATION
} from './balance.js';

// UI constants
export {
    COLOR_HP_BAR_BG, COLOR_HP_BAR_FILL, COLOR_PLAYER_HIT_TINT, COLOR_ENEMY_HIT_TINT,
    COLOR_CHEST_HP_BAR_BG, COLOR_CHEST_HP_BAR_FILL, COLOR_CHEST_BROKEN_TINT,
    COLOR_BOSS_DEATH_TINT, COLOR_GOLD, COLOR_BG_DARK,
    COLOR_METEOR, COLOR_CHEMICAL_CLOUD, COLOR_SOUL_STRIKE, COLOR_ACID_FLASK,
    COLOR_HOLY_NOVA, COLOR_TOXIC_PUDDLE, COLOR_TOXIC_PUDDLE_BORDER, COLOR_HEAL_ZONE,
    HP_BAR_OFFSET_Y, BOSS_NAME_OFFSET_Y
} from './ui.js';
