export const NPC_DB = {
    elder: {
        name: 'Village Elder',
        nameRu: 'Старейшина',
        nameDe: 'Dorfältester',
        texKey: 'npc_elder',
        biome: 'forest',
        x: 680, y: 800,
        greeting: 'Brave adventurer, our village needs your help!',
        greetingRu: 'Храбрый странник, нашей деревне нужна твоя помощь!',
        greetingDe: 'Mutiger Abenteuerer, unser Dorf braucht deine Hilfe!',
        quests: ['kill_goblins', 'kill_rats', 'treant_boss', 'cave_spiders', 'giant_bat_boss']
    },
    miner: {
        name: 'Old Miner',
        nameRu: 'Старый Шахтёр',
        nameDe: 'Alter Bergmann',
        texKey: 'npc_miner',
        biome: 'mine',
        x: 400, y: 160,
        greeting: 'The mines hold treasure... and danger.',
        greetingRu: 'Шахты хранят сокровища... и опасность.',
        greetingDe: 'Die Minen bergen Schätze... und Gefahren.',
        quests: ['kill_skeletons', 'mine_chests', 'skeleton_lord_boss'],
        hideName: true
    },
    villager: {
        name: 'Village Guard',
        nameRu: 'Стражник Деревни',
        nameDe: 'Dorfwache',
        texKey: 'npc_elder',
        biome: 'village',
        x: 400, y: 200,
        greeting: 'The village is overrun! Help us clear the camps!',
        greetingRu: 'Деревня захвачена! Помогите очистить лагеря!',
        greetingDe: 'Das Dorf ist überrennt! Hilf uns, die Lager zu säubern!',
        quests: ['clear_village_camps', 'defeat_village_boss'],
        hideName: true,
        condition: '!isRestored' // Only show when village is NOT restored
    },
    elder_dying: {
        name: 'Dying Elder',
        nameRu: 'Умирающий Старейшина',
        nameDe: 'Sterbender Ältester',
        texKey: 'npc_elder_dying',
        biome: 'depths',
        x: 400, y: 100,
        greeting: 'The Lich King... he controls everything below. Please, stop him...',
        greetingRu: 'Король Лич... он контролирует всё внизу. Пожалуйста, остановите его...',
        greetingDe: 'Der Lichkönig... er kontrolliert alles darunter. Bitte, stoppt ihn...',
        quests: ['depths_catacombs', 'depths_library', 'depths_forge', 'depths_judgment', 'depths_throne'],
        hideName: true,
        condition: 'isThriving'
    },
    village_merchant: {
        name: 'Merchant',
        nameRu: 'Торговец',
        nameDe: 'Händler',
        texKey: 'npc_elder',
        biome: 'village',
        x: 300, y: 500,
        greeting: 'Welcome to my shop! I have wares from all lands.',
        greetingRu: 'Добро пожаловать в мой магазин! У меня товары со всех земель.',
        greetingDe: 'Willkommen in meinem Laden! Ich habe Waren aus allen Landen.',
        quests: [],
        hideName: true,
        condition: 'isRestored'
    },
    village_child2: {
        name: 'Village Child',
        nameRu: 'Деревенский Ребёнок',
        nameDe: 'Dorfkind',
        texKey: 'child_npc',
        biome: 'village',
        x: 550, y: 700,
        greeting: 'Look! A hero! Can I play with you?',
        greetingRu: 'Смотри! Герой! Можно поиграть с тобой?',
        greetingDe: 'Schau! Ein Held! Kann ich mit dir spielen?',
        quests: [],
        hideName: true,
        condition: 'isRestored'
    },
    grown_child: {
        name: 'Grown Child',
        nameRu: 'Выросший Ребёнок',
        nameDe: 'Gewachsenes Kind',
        texKey: 'npc_elder',
        biome: 'depths',
        x: 200, y: 500,
        greeting: 'The catacombs hold many secrets. Search the chests for ancient relics.',
        greetingRu: 'Катакомбы хранят много секретов. Ищите в сундуках древние реликвии.',
        greetingDe: 'Die Katakomben bergen viele Geheimnisse. Suche in den Truhen nach alten Relikten.',
        quests: ['depths_exploration'],
        hideName: true,
        condition: 'isThriving'
    },
    forest_guard: {
        name: 'Forest Guard',
        nameRu: 'Лесной Страж',
        nameDe: 'Forstwache',
        texKey: 'npc_elder',
        biome: 'forest',
        x: 350, y: 850,
        greeting: 'The cursed lands to the east claim more victims each day. Someone must stop the corruption.',
        greetingRu: 'Проклятые земли на востоке забирают всё больше жертв. Кто-то должен остановить порчу.',
        greetingDe: 'Die verfluchten Lande im Osten fordern jeden Tag mehr Opfer. Jemand muss die Verderbnis aufhalten.',
        quests: ['cursed_swamp', 'cursed_forest'],
        hideName: true,
        condition: 'depthsBossDefeated'
    },
    old_hunter: {
        name: 'Old Hunter',
        nameRu: 'Старый Охотник',
        nameDe: 'Alter Jäger',
        texKey: 'npc_miner',
        biome: 'cursed',
        x: 450, y: 300,
        greeting: 'The swamp teems with creatures. Be careful — their venom is deadly.',
        greetingRu: 'Болото кишит тварями. Будьте осторожны — их яд смертелен.',
        greetingDe: 'Das Sumpfgeblobde wimmelt von Kreaturen. Vorsicht — ihr Gift ist tödlich.',
        quests: ['cursed_swamp', 'cursed_field'],
        hideName: true
    },
    priestess: {
        name: 'Priestess',
        nameRu: 'Жрица',
        nameDe: 'Priesterin',
        texKey: 'npc_elder',
        biome: 'cursed',
        x: 450, y: 1400,
        greeting: 'The ancient evil corrupts all it touches. Only holy light can cleanse this land.',
        greetingRu: 'Древнее зло порчает всё, к чему прикасается. Только святой свет может очистить эту землю.',
        greetingDe: 'Das uralte Übel verderbt alles, was es berührt. Nur heiligem Licht kann dieses Land reinigen.',
        quests: ['cursed_temple', 'cursed_artifacts'],
        hideName: true
    },
    captured_knight: {
        name: 'Captured Knight',
        nameRu: 'Пленный Рыцарь',
        nameDe: 'Gefangener Ritter',
        texKey: 'npc_elder',
        biome: 'cursed',
        x: 200, y: 2100,
        greeting: 'I was captured by the undead. Free me and I will help you defeat the ancient evil.',
        greetingRu: 'Меня захватили нежить. Освободите меня, и я помогу вам победить древнее зло.',
        greetingDe: 'Ich wurde von den Untoten gefangen genommen. Befreit mich, und ich werde euch helfen, das uralte Übel zu besiegen.',
        quests: ['cursed_field', 'cursed_heart'],
        hideName: true
    },
    fallen_angel: {
        name: 'Fallen Angel',
        nameRu: 'Павший Ангел',
        nameDe: 'Gefallener Engel',
        texKey: 'npc_elder',
        biome: 'shadow',
        x: 400, y: 200,
        greeting: 'The Shadow King has corrupted this dimension. We must restore the light.',
        greetingRu: 'Король Теней порчает это измерение. Мы должны вернуть свет.',
        greetingDe: 'Der Schattenkönig hat diese Dimension korrumpiert. Wir müssen das Licht zurückbringen.',
        quests: ['shadow_stalkers', 'shadow_mirrors', 'shadow_throne'],
        hideName: true
    },
    trapped_soul: {
        name: 'Trapped Soul',
        nameRu: 'Пленная Душа',
        nameDe: 'Gefangene Seele',
        texKey: 'npc_miner',
        biome: 'shadow',
        x: 200, y: 1000,
        greeting: 'I am trapped between dimensions. Help me find the rift cores to break free.',
        greetingRu: 'Я пленён между измерениями. Помогите найти ядра разломов, чтобы освободиться.',
        greetingDe: 'Ich bin zwischen Dimensionen gefangen. Hilf mir, die Risskerne zu finden, um frei zu werden.',
        quests: ['shadow_rifts', 'shadow_fragments'],
        hideName: true
    },
    rift_scout: {
        name: 'Rift Scout',
        nameRu: 'Разведчик Разломов',
        nameDe: 'Rissaufklärer',
        texKey: 'npc_elder',
        biome: 'shadow',
        x: 400, y: 2200,
        greeting: 'The rifts are unstable. Close them before more shadows escape.',
        greetingRu: 'Разломы нестабильны. Закройте их, прежде чем вырвется больше теней.',
        greetingDe: 'Die Risse sind instabil. Schließe sie, bevor weitere Schatten entweichen.',
        quests: ['shadow_king_quest', 'shadow_fragments'],
        hideName: true
    },
    ghost_advisor: {
        name: 'Ghost Advisor',
        nameRu: 'Призрачный Советник',
        nameDe: 'Geisterberater',
        texKey: 'npc_elder',
        biome: 'tower',
        x: 400, y: 100,
        greeting: 'The tower stands tall, but its king is fallen. Free him from his curse.',
        greetingRu: 'Башня стоит величественно, но её король пал. Освободите его от проклятия.',
        greetingDe: 'Der Turm steht hoch, aber sein König ist gefallen. Befreie ihn von seinem Fluch.',
        quests: ['tower_knights', 'tower_mages', 'tower_king'],
        hideName: true
    },
    trapped_prince: {
        name: 'Trapped Prince',
        nameRu: 'Пленный Принц',
        nameDe: 'Gefangener Prinz',
        texKey: 'npc_miner',
        biome: 'tower',
        x: 300, y: 2400,
        greeting: 'I am trapped between dimensions. Help me find the tower hearts to break free.',
        greetingRu: 'Я пленён между измерениями. Помогите найти сердца башни, чтобы освободиться.',
        greetingDe: 'Ich bin zwischen Dimensionen gefangen. Hilf mir, die Turmherne zu finden, um frei zu werden.',
        quests: ['tower_guards', 'tower_relics'],
        hideName: true
    },
    tower_sage: {
        name: 'Tower Sage',
        nameRu: 'Башенный Мудрец',
        nameDe: 'Turmweise',
        texKey: 'npc_elder',
        biome: 'tower',
        x: 500, y: 3600,
        greeting: 'The fallen king guards the throne. Only the worthy can free him.',
        greetingRu: 'Павший Король охраняет трон. Только достойный может освободить его.',
        greetingDe: 'Der gefallene König bewacht den Thron. Nur der Würdige kann ihn befreien.',
        quests: ['tower_counsel', 'tower_king'],
        hideName: true
    },
    elder_depths: {
        name: 'Dying Elder',
        nameRu: 'Умирающий Старейшина',
        nameDe: 'Sterbender Ältester',
        texKey: 'npc_elder_dying',
        biome: 'depths',
        x: 400, y: 100,
        greeting: 'The shadow comes from here. Go deeper.',
        greetingRu: 'Тень идёт отсюда. Иди дальше.',
        greetingDe: 'Der Schatten kommt von hier. Geh tiefer.',
        quests: [],
        hideName: true,
        condition: 'isThriving'
    },
    fallen_angel_npc: {
        name: 'Fallen Angel',
        nameRu: 'Павший Ангел',
        nameDe: 'Gefallener Engel',
        texKey: 'fallen_angel',
        biome: 'shadow',
        x: 400, y: 300,
        greeting: 'Behind the shadows stands a tower. Run.',
        greetingRu: 'За тенями стоит башня. Беги.',
        greetingDe: 'Hinter den Schatten steht ein Turm. Renn.',
        quests: [],
        hideName: true
    }
};

export const QUEST_DB = {
    kill_goblins: {
        name: 'Goblin Trouble',
        nameRu: 'Проблемы с Гоблинами',
        nameDe: 'Goblin-Ärger',
        type: 'kill',
        target: 'goblin',
        count: 10,
        biome: 'forest',
        description: 'The goblins have been raiding our supplies. Put an end to their mischief.',
        descriptionRu: 'Гоблины грабят наши запасы. Положите конец их шалостям.',
        descriptionDe: 'Die Goblinen plündern unsere Vorräte. Mach ihren Machenschaften ein Ende.',
        rewards: { exp: 80, accountExp: 30 },
        rewardItems: ['iron_sword', 'leather_armor'],
        prerequisite: null
    },
    kill_rats: {
        name: 'Rat Pack',
        nameRu: 'Крысиная Стая',
        nameDe: 'Rattenhorde',
        type: 'kill',
        target: 'rat',
        count: 15,
        biome: 'forest',
        description: 'A swarm of rats has infested the forest. They must be stopped.',
        descriptionRu: 'Стая крыс захлестнула лес. Их нужно остановить.',
        descriptionDe: 'Eine Rattenschwärme hat den Wald befallen. Sie müssen aufgehalten werden.',
        rewards: { exp: 100, accountExp: 40 },
        rewardItems: ['ruby_ring'],
        prerequisite: null
    },
    treant_boss: {
        name: 'The Ancient One',
        nameRu: 'Древнее Существо',
        nameDe: 'Das Uralte',
        type: 'kill',
        target: 'ancient_treant',
        count: 1,
        biome: 'arena',
        description: 'The Ancient Treant guards the path forward. Only by defeating it can you reach the mines.',
        descriptionRu: 'Древний Трент охраняет путь вперёд. Только победив его вы доберётесь до шахт.',
        descriptionDe: 'Der Uralte Treant bewacht den Weg nach vorn. Nur durch seinen Besieg gelangst du zu den Minen.',
        rewards: { exp: 300, accountExp: 100, talentPoints: 1 },
        rewardItems: ['flame_blade'],
        prerequisite: null
    },
    cave_spiders: {
        name: 'Spider Nest',
        nameRu: 'Паучье Гнездо',
        nameDe: 'Spinnennest',
        type: 'kill',
        target: 'cave_spider',
        count: 12,
        biome: 'cave',
        description: 'Massive spiders infest the cave. Clear their nest before they spread.',
        descriptionRu: 'Огромные пауки заполонили пещеру. Очистите их гнездо, прежде чем они расплодятся.',
        descriptionDe: 'Riesige Spinnen bevölkern die Höhle. Räume ihr Nest bevor sie sich ausbreiten.',
        rewards: { exp: 150, accountExp: 60 },
        rewardItems: ['sapphire_ring'],
        prerequisite: 'treant_boss'
    },
    giant_bat_boss: {
        name: 'The Swarm Lord',
        nameRu: 'Повелитель Стай',
        nameDe: 'Der Schwarmherr',
        type: 'kill',
        target: 'giant_bat',
        count: 1,
        biome: 'cave',
        description: 'The Giant Bat commands the cave creatures. End its reign.',
        descriptionRu: 'Гигантская Летучая Мыши командует обитателями пещеры. Положите конец её правлению.',
        descriptionDe: 'Die Riesen-Fledermaus kommandiert die Höhlenbewohner. Beende ihre Herrschaft.',
        rewards: { exp: 400, accountExp: 150, talentPoints: 2 },
        rewardItems: ['flame_blade'],
        prerequisite: 'treant_boss'
    },
    kill_skeletons: {
        name: 'Bone Patrol',
        nameRu: 'Костяной Патруль',
        nameDe: 'Knochenpatrouille',
        type: 'kill',
        target: 'skeleton_warrior',
        count: 10,
        biome: 'mine',
        description: 'The skeleton warriors guard the deepest mines. Break through their ranks.',
        descriptionRu: 'Скелеты-воины охраняют глубочайшие шахты. Прорвитесь сквозь их ряды.',
        descriptionDe: 'Die Skelettkrieger bewachen die tiefsten Minen. Brich durch ihre Reihen.',
        rewards: { exp: 120, accountExp: 50 },
        rewardItems: ['iron_armor'],
        prerequisite: 'treant_boss'
    },
    mine_chests: {
        name: 'Treasure Hunter',
        nameRu: 'Охотник за Сокровищами',
        nameDe: 'Schatzjäger',
        type: 'collect',
        target: 'mine_chest',
        count: 5,
        biome: 'mine',
        description: 'The old miners left hidden chests throughout the mines. Find 5 of them.',
        descriptionRu: 'Старые шахтёры спрятали сундуки по всей шахте. Найдите 5 из них.',
        descriptionDe: 'Die alten Bergleute haben versteckte Truhen in den Minen hinterlassen. Finde 5 davon.',
        rewards: { exp: 150, accountExp: 60 },
        rewardItems: ['dragon_scale'],
        prerequisite: 'treant_boss'
    },
    skeleton_lord_boss: {
        name: 'The Bone King',
        nameRu: 'Костяной Король',
        nameDe: 'Der Knochenkönig',
        type: 'kill',
        target: 'skeleton_lord',
        count: 1,
        biome: 'mine_boss',
        description: 'The Skeleton Lord rules the dead. End his eternal reign.',
        descriptionRu: 'Повелитель Скелетов правит мёртвыми. Положите конец его вечному правлению.',
        descriptionDe: 'Der Skelett-Lord herrscht über die Toten. Beende seine ewige Herrschaft.',
        rewards: { exp: 500, accountExp: 200, talentPoints: 2 },
        rewardItems: ['crown'],
        prerequisite: 'treant_boss'
    },
    clear_village_camps: {
        name: 'Purge the Corruption',
        nameRu: 'Очистить Заражение',
        nameDe: 'Die Verunreinigung beseitigen',
        type: 'kill',
        target: 'village_brute',
        count: 8,
        biome: 'village',
        description: 'Clear all infected camps in the village to restore peace.',
        descriptionRu: 'Очистите все заражённые лагеря в деревне, чтобы вернуть мир.',
        descriptionDe: 'Säubere alle infizierten Lager im Dorf, um den Frieden wiederherzustellen.',
        rewards: { exp: 200, accountExp: 80, talentPoints: 1 },
        rewardItems: ['iron_armor'],
        prerequisite: 'skeleton_lord_boss'
    },
    defeat_village_boss: {
        name: 'The Demon Within',
        nameRu: 'Демон Внутри',
        nameDe: 'Der Dämon in Dir',
        type: 'kill',
        target: 'purple_demon',
        count: 1,
        biome: 'village',
        description: 'The Purple Demon controls the village. Defeat it to free the souls.',
        descriptionRu: 'Фиолетовый Демон контролирует деревню. Победите его, чтобы освободить души.',
        descriptionDe: 'Der Lila Dämon kontrolliert das Dorf. Besiege ihn, um die Seelen zu befreien.',
        rewards: { exp: 600, accountExp: 250, talentPoints: 2 },
        rewardItems: ['flame_blade'],
        prerequisite: 'clear_village_camps'
    },
    depths_catacombs: {
        name: 'Bone Patrol',
        nameRu: 'Костяной Патруль',
        nameDe: 'Knochenpatrouille',
        type: 'kill',
        target: 'crypt_soldier',
        count: 15,
        biome: 'depths',
        description: 'The crypt soldiers guard the deepest catacombs. Break through their ranks.',
        descriptionRu: 'Криптовые солдаты охраняют глубочайшие катакомбы. Прорвитесь сквозь их ряды.',
        descriptionDe: 'Die Kryptsoldaten bewachen die tiefsten Katakomben. Brich durch ihre Reihen.',
        rewards: { exp: 250, accountExp: 100, talentPoints: 1 },
        rewardItems: ['dark_rune'],
        prerequisite: 'defeat_village_boss'
    },
    depths_library: {
        name: 'Forbidden Knowledge',
        nameRu: 'Запретные Знания',
        nameDe: 'Verbotenes Wissen',
        type: 'kill',
        target: 'necro_mage',
        count: 10,
        biome: 'depths',
        description: 'The necro mages guard the library of the dead. Silence their dark incantations.',
        descriptionRu: 'Некромаги охраняют библиотеку мёртвых. Утихоморите их тёмные заклинания.',
        descriptionDe: 'Die Nekromagier bewachen die Bibliothek der Toten. Still dunkle Zaubersprüche.',
        rewards: { exp: 280, accountExp: 110, talentPoints: 1 },
        rewardItems: ['soul_shard'],
        prerequisite: 'depths_catacombs'
    },
    depths_forge: {
        name: 'The Dark Forge',
        nameRu: 'Тёмная Кузня',
        nameDe: 'Die Dunkle Schmiede',
        type: 'kill',
        target: 'grave_knight',
        count: 8,
        biome: 'depths',
        description: 'The grave knights protect the dark forge. Destroy them to claim its secrets.',
        descriptionRu: 'Могильные рыцари защищают тёмную кузню. Уничтожьте их, чтобы забрать её секреты.',
        descriptionDe: 'Die Grabritter beschützen die dunkle Schmiede. Zerstöre sie, um ihre Geheimnisse zu beanspruchen.',
        rewards: { exp: 300, accountExp: 120, talentPoints: 1 },
        rewardItems: ['cursed_iron'],
        prerequisite: 'depths_library'
    },
    depths_judgment: {
        name: 'Soul Harvest',
        nameRu: 'Жатва Душ',
        nameDe: 'Seelenernte',
        type: 'kill',
        target: 'soul_eater',
        count: 5,
        biome: 'depths',
        description: 'The soul eaters consume the dead. End their feast before they grow too strong.',
        descriptionRu: 'Пожиратели душ пожирают мёртвых. Остановите их пир, прежде чем они станут слишком сильными.',
        descriptionDe: 'Die Seelenfresser verschlingen die Toten. Beende ihr Fest, bevor sie zu stark werden.',
        rewards: { exp: 350, accountExp: 130, talentPoints: 1 },
        rewardItems: ['blood_crystal'],
        prerequisite: 'depths_forge'
    },
    depths_throne: {
        name: 'The Lich King',
        nameRu: 'Король Лич',
        nameDe: 'Der Lichkönig',
        type: 'kill',
        target: 'lich_king',
        count: 1,
        biome: 'depths_boss',
        description: 'The Lich King rules the dead. End his eternal reign.',
        descriptionRu: 'Король Лич правит мёртвыми. Положите конец его вечному правлению.',
        descriptionDe: 'Der Lichkönig herrscht über die Toten. Beende seine ewige Herrschaft.',
        rewards: { exp: 2000, accountExp: 500, talentPoints: 3 },
        rewardItems: ['crown'],
        prerequisite: 'depths_judgment'
    },
    depths_exploration: {
        name: 'Relic Hunter',
        nameRu: 'Охотник за Реликвиями',
        nameDe: 'Reliksjäger',
        type: 'collect',
        target: 'depths_chest',
        count: 5,
        biome: 'depths',
        description: 'The catacombs hold many secrets. Find 5 ancient chests to uncover their treasures.',
        descriptionRu: 'Катакомбы хранят много секретов. Найдите 5 древних сундуков, чтобы открыть их сокровища.',
        descriptionDe: 'Die Katakomben bergen viele Geheimnisse. Finde 5 alte Truhen, um ihre Schätze zu enthüllen.',
        rewards: { exp: 200, accountExp: 80 },
        rewardItems: ['dark_rune'],
        prerequisite: 'depths_catacombs'
    },
    cursed_swamp: {
        name: 'Swamp Purge',
        nameRu: 'Очищение Болота',
        nameDe: 'Sumpfsäuberung',
        type: 'kill',
        target: 'swamp_thug',
        count: 15,
        biome: 'cursed',
        description: 'The swamp thugs guard the cursed lands. Break through their ranks.',
        descriptionRu: 'Болотные головорезы охраняют проклятые земли. Прорвитесь сквозь их ряды.',
        descriptionDe: 'Die Sumpf-Schläger bewachen die verfluchten Lande. Brich durch ihre Reihen.',
        rewards: { exp: 300, accountExp: 120, talentPoints: 1 },
        rewardItems: ['grave_iron'],
        prerequisite: 'depths_throne'
    },
    cursed_forest: {
        name: 'Spider Nest',
        nameRu: 'Паучье Гнездо',
        nameDe: 'Spinnennest',
        type: 'kill',
        target: 'venom_spider',
        count: 12,
        biome: 'cursed',
        description: 'Venom spiders infest the cursed forest. Clear their nest before they spread.',
        descriptionRu: 'Ядовитые пауки заполонили проклятый лес. Очистите их гнездо, прежде чем они расплодятся.',
        descriptionDe: 'Giftspinnen bevölkern den verfluchten Wald. Räume ihr Nest, bevor sie sich ausbreiten.',
        rewards: { exp: 320, accountExp: 130, talentPoints: 1 },
        rewardItems: ['venom_sac'],
        prerequisite: 'depths_throne'
    },
    cursed_field: {
        name: 'Undead Horde',
        nameRu: 'Орда Нежити',
        nameDe: 'Untotenhorde',
        type: 'kill',
        target: 'zombie_knight',
        count: 10,
        biome: 'cursed',
        description: 'Zombie knights patrol the cursed fields. Destroy them to free the land.',
        descriptionRu: 'Рыцари-зомби патрулируют проклятые поля. Уничтожьте их, чтобы освободить землю.',
        descriptionDe: 'Zombie-Ritter patrouillieren die verfluchten Felder. Zerstöre sie, um das Land zu befreien.',
        rewards: { exp: 350, accountExp: 140, talentPoints: 1 },
        rewardItems: ['grave_iron'],
        prerequisite: 'cursed_swamp'
    },
    cursed_temple: {
        name: 'Temple Guardians',
        nameRu: 'Стражи Храма',
        nameDe: 'Tempelwächter',
        type: 'kill',
        target: 'corrupted_priest',
        count: 8,
        biome: 'cursed',
        description: 'Corrupted priests defile the ancient temple. Cleanse it with holy fire.',
        descriptionRu: 'Проклятые жрецы оскверняют древний храм. Очистите его священным огнём.',
        descriptionDe: 'Verfluchte Priester entweihen den alten Tempel. Reinige ihn mit heiligem Feuer.',
        rewards: { exp: 380, accountExp: 150, talentPoints: 1 },
        rewardItems: ['holy_shard'],
        prerequisite: 'cursed_field'
    },
    cursed_heart: {
        name: 'The Ancient Evil',
        nameRu: 'Древнее Зло',
        nameDe: 'Das Uralte Übel',
        type: 'kill',
        target: 'ancient_evil',
        count: 1,
        biome: 'cursed_boss',
        description: 'The Ancient Evil corrupts the land. End its reign of terror.',
        descriptionRu: 'Древнее зло порчает землю. Положите конец его террору.',
        descriptionDe: 'Das uralte Übel verderbt das Land. Beende seinen Schreckensherrschaft.',
        rewards: { exp: 2500, accountExp: 600, talentPoints: 3 },
        rewardItems: ['crown'],
        prerequisite: 'cursed_temple'
    },
    cursed_artifacts: {
        name: 'Relic Hunter',
        nameRu: 'Охотник за Реликвиями',
        nameDe: 'Reliksjäger',
        type: 'collect',
        target: 'cursed_chest',
        count: 3,
        biome: 'cursed',
        description: 'The cursed lands hide ancient artifacts. Find 3 chests to uncover their treasures.',
        descriptionRu: 'Проклятые земли скрывают древние артефакты. Найдите 3 сундука, чтобы открыть их сокровища.',
        descriptionDe: 'Die verfluchten Lande verbergen uralte Artefakte. Finde 3 Truhen, um ihre Schätze zu enthüllen.',
        rewards: { exp: 250, accountExp: 100 },
        rewardItems: ['holy_shard'],
        prerequisite: 'cursed_swamp'
    },
    shadow_stalkers: {
        name: 'Shadow Purge',
        nameRu: 'Очищение Теней',
        nameDe: 'Schattensäuberung',
        type: 'kill',
        target: 'shadow_stalker',
        count: 15,
        biome: 'shadow',
        description: 'Shadow stalkers hunt between dimensions. End their relentless pursuit.',
        descriptionRu: 'Тени-следопыты охотятся между измерениями. Остановите их неутомимую погоню.',
        descriptionDe: 'Schattenpirscher jagen zwischen Dimensionen. Beende ihre rastlose Verfolgung.',
        rewards: { exp: 400, accountExp: 160, talentPoints: 1 },
        rewardItems: ['rift_core'],
        prerequisite: 'cursed_heart'
    },
    shadow_mirrors: {
        name: 'Mirror Illusions',
        nameRu: 'Зеркальные Иллюзии',
        nameDe: 'Spiegelillusionen',
        type: 'kill',
        target: 'mirror_image',
        count: 12,
        biome: 'shadow',
        description: 'Mirror images confuse and deceive. Destroy the illusions before they overwhelm you.',
        descriptionRu: 'Зеркальные отражения сбивают с толку и обманывают. Уничтожьте иллюзии, прежде чем они подавят вас.',
        descriptionDe: 'Spiegelbilder verwirren und täuschen. Zerstöre die Illusionen, bevor sie dich überwältigen.',
        rewards: { exp: 420, accountExp: 170, talentPoints: 1 },
        rewardItems: ['mirror_fragment'],
        prerequisite: 'shadow_stalkers'
    },
    shadow_rifts: {
        name: 'Rift Closure',
        nameRu: 'Закрытие Разломов',
        nameDe: 'Rissverschluss',
        type: 'kill',
        target: 'rift_walker',
        count: 10,
        biome: 'shadow',
        description: 'Rift walkers maintain the dimensional tears. Destroy them to seal the rifts.',
        descriptionRu: 'Скитальцы разломов поддерживают меж维度ные разрывы. Уничтожьте их, чтобы закрыть разломы.',
        descriptionDe: 'Risswanderer halten die dimensions Risse aufrecht. Zerstöre sie, um die Risse zu versiegeln.',
        rewards: { exp: 450, accountExp: 180, talentPoints: 1 },
        rewardItems: ['rift_core'],
        prerequisite: 'shadow_stalkers'
    },
    shadow_king_quest: {
        name: 'Shadow Purification',
        nameRu: 'Очищение Теней',
        nameDe: 'Schattenreinigung',
        type: 'kill',
        target: 'shadow_mage',
        count: 8,
        biome: 'shadow',
        description: 'Shadow mages fuel the Shadow King\'s power. Weaken him by destroying his sources.',
        descriptionRu: 'Теневые маги питают силу Короля Теней. Ослабьте его, уничтожив его источники.',
        descriptionDe: 'Schattenmagier nähren die Kraft des Schattenkönigs. Schwäche ihn, indem du seine Quellen zerstörst.',
        rewards: { exp: 500, accountExp: 200, talentPoints: 1 },
        rewardItems: ['shadow_crystal'],
        prerequisite: 'shadow_rifts'
    },
    shadow_throne: {
        name: 'The Shadow King',
        nameRu: 'Король Теней',
        nameDe: 'Der Schattenkönig',
        type: 'kill',
        target: 'shadow_king',
        count: 1,
        biome: 'shadow_boss',
        description: 'The Shadow King commands all darkness. End his reign of terror.',
        descriptionRu: 'Король Теней повелевает всей тьмой. Положите конец его террору.',
        descriptionDe: 'Der Schattenkönig befiehlt alle Dunkelheit. Beende seine Schreckensherrschaft.',
        rewards: { exp: 3000, accountExp: 700, talentPoints: 3 },
        rewardItems: ['crown'],
        prerequisite: 'shadow_king_quest'
    },
    shadow_fragments: {
        name: 'Dimensional Fragments',
        nameRu: 'Фрагменты Измерения',
        nameDe: 'Dimensionsfragmente',
        type: 'collect',
        target: 'shadow_chest',
        count: 3,
        biome: 'shadow',
        description: 'The shadow dimension hides powerful artifacts. Find 3 chests to uncover their treasures.',
        descriptionRu: 'Теневое измерение скрывает могущественные артефакты. Найдите 3 сундука, чтобы открыть их сокровища.',
        descriptionDe: 'Die Schattendimension verbirgt mächtige Artefakte. Finde 3 Truhen, um ihre Schätze zu enthüllen.',
        rewards: { exp: 350, accountExp: 140 },
        rewardItems: ['shadow_crystal'],
        prerequisite: 'shadow_stalkers'
    },
    tower_knights: {
        name: 'Tower Purge',
        nameRu: 'Очищение Башни',
        nameDe: 'Turmsäuberung',
        type: 'kill',
        target: 'tower_knight',
        count: 15,
        biome: 'tower',
        description: 'Tower knights guard the ancient tower. Break through their ranks.',
        descriptionRu: 'Башенные рыцари охраняют древнюю башню. Прорвитесь сквозь их ряды.',
        descriptionDe: 'Turmritter bewachen den alten Turm. Brich durch ihre Reihen.',
        rewards: { exp: 500, accountExp: 200, talentPoints: 1 },
        rewardItems: ['ancient_steel'],
        prerequisite: 'shadow_throne'
    },
    tower_mages: {
        name: 'Arcane Silence',
        nameRu: 'Магическое Молчание',
        nameDe: 'Arkanes Schweigen',
        type: 'kill',
        target: 'tower_mage',
        count: 12,
        biome: 'tower',
        description: 'Tower mages fuel the curse. Silence their dark incantations.',
        descriptionRu: 'Башенные маги питают проклятие. Утихоморите их тёмные заклинания.',
        descriptionDe: 'Turmmagier nähren den Fluch. Stille ihre dunklen Zaubersprüche.',
        rewards: { exp: 520, accountExp: 210, talentPoints: 1 },
        rewardItems: ['tower_rune'],
        prerequisite: 'tower_knights'
    },
    tower_guards: {
        name: 'Royal Guard',
        nameRu: 'Королевская Стража',
        nameDe: 'Königsgarde',
        type: 'kill',
        target: 'royal_guard',
        count: 10,
        biome: 'tower',
        description: 'Royal guards protect the tower\'s secrets. Destroy them to claim its treasures.',
        descriptionRu: 'Королевская стража защищает секреты башни. Уничтожьте их, чтобы забрать сокровища.',
        descriptionDe: 'Die Königsgarde bewacht die Geheimnisse des Turms. Zerstöre sie, um seine Schätze zu beanspruchen.',
        rewards: { exp: 550, accountExp: 220, talentPoints: 1 },
        rewardItems: ['paladin_oath'],
        prerequisite: 'tower_knights'
    },
    tower_counsel: {
        name: 'Dark Council',
        nameRu: 'Тёмный Совет',
        nameDe: 'Dunkler Rat',
        type: 'kill',
        target: 'dark_counselor',
        count: 8,
        biome: 'tower',
        description: 'Dark counselors whisper lies to the fallen king. Silence them.',
        descriptionRu: 'Тёмные советники шепчут ложь павшему королю. Утихоморите их.',
        descriptionDe: 'Dunkle Räte flüstern Lügen dem gefallenen König zu. Stille sie.',
        rewards: { exp: 600, accountExp: 240, talentPoints: 1 },
        rewardItems: ['tower_heart'],
        prerequisite: 'tower_guards'
    },
    tower_king: {
        name: 'The Fallen King',
        nameRu: 'Павший Король',
        nameDe: 'Der Gefallene König',
        type: 'kill',
        target: 'fallen_king',
        count: 1,
        biome: 'tower_boss',
        description: 'The Fallen King guards the tower. Free him from his eternal curse.',
        descriptionRu: 'Павший Король охраняет башню. Освободите его от вечного проклятия.',
        descriptionDe: 'Der gefallene König bewacht den Turm. Befreie ihn von seinem ewigen Fluch.',
        rewards: { exp: 4000, accountExp: 900, talentPoints: 3 },
        rewardItems: ['crown'],
        prerequisite: 'tower_counsel'
    },
    tower_relics: {
        name: 'Tower Relics',
        nameRu: 'Реликвии Башни',
        nameDe: 'Turmrelikte',
        type: 'collect',
        target: 'tower_chest',
        count: 3,
        biome: 'tower',
        description: 'The tower hides ancient relics. Find 3 chests to uncover their treasures.',
        descriptionRu: 'Башня скрывает древние реликвии. Найдите 3 сундука, чтобы открыть их сокровища.',
        descriptionDe: 'Der Turm verbirgt uralte Relikte. Finde 3 Truhen, um ihre Schätze zu enthüllen.',
        rewards: { exp: 400, accountExp: 160 },
        rewardItems: ['tower_rune'],
        prerequisite: 'tower_knights'
    },
    throne_final: {
        name: 'The Eternity Lord',
        nameRu: 'Повелитель Вечности',
        nameDe: 'Der Herr der Ewigkeit',
        type: 'kill',
        target: 'eternity_lord',
        count: 1,
        biome: 'throne',
        description: 'The Eternity Lord guards the throne. End his reign and decide the fate of the world.',
        descriptionRu: 'Повелитель Вечности охраняет трон. Положите конец его правлению и решите судьбу мира.',
        descriptionDe: 'Der Herr der Ewigkeit bewacht den Thron. Beende seine Herrschaft und entscheide das Schicksal der Welt.',
        rewards: { exp: 10000, accountExp: 2000, talentPoints: 5 },
        rewardItems: ['crown_of_eternity', 'sword_of_eternity', 'amulet_of_eternity'],
        prerequisite: 'tower_king'
    }
};

export const CART_DRIVER_NPC = {
    cart_driver: {
        name: 'Mysterious Cart Driver',
        nameRu: 'Загадочный Извозчик',
        nameDe: 'Geheimnisvoller Kutscher',
        texKey: 'npc_cart_driver',
        biome: 'forest',
        x: 250, y: 80,
        greeting: 'That key... I know where it leads. Hop in.',
        greetingRu: 'Этот ключ... я знаю куда он ведёт. Запрыгивай.',
        greetingDe: 'Dieser Schlüssel... ich weiß wohin er führt. Steig ein.',
        requiresItem: 'secret_key',
        isCartDriver: true
    }
};
