export const SPELLS = {
    fireball: {
        key: 'fireball',
        name: 'Fireball',
        nameRu: 'Огненный Шар',
        nameDe: 'Feuerball',
        slot: 'Q',
        corruptionCost: 12,
        cooldown: 1.5,
        damage: 55,
        speed: 400,
        range: 450,
        color: 0xe74c3c,
        description: 'Hurls a blazing fireball dealing spell damage'
    },
    shield: {
        key: 'shield',
        name: 'Arcane Shield',
        nameRu: 'Щит',
        nameDe: 'Arkaner Schild',
        slot: 'W',
        corruptionCost: 20,
        cooldown: 8.0,
        absorption: 50,
        duration: 5.0,
        color: 0x3498db,
        description: 'Absorbs damage for 5 seconds'
    },
    heal: {
        key: 'heal',
        name: 'Heal',
        nameRu: 'Исцеление',
        nameDe: 'Heilung',
        slot: 'E',
        corruptionCost: 20,
        cooldown: 8.0,
        healPercent: 0.40,
        color: 0x2ecc71,
        description: 'Restores 40% of max HP with holy light'
    },
    acid_flask: {
        key: 'acid_flask',
        name: 'Acid Flask',
        nameRu: 'Кислотная Бутылка',
        nameDe: 'Säureflasche',
        slot: 'Q',
        corruptionCost: 12,
        cooldown: 2.0,
        damage: 45,
        range: 250,
        radius: 50,
        dot: 8,
        dotDuration: 2.0,
        color: 0x27ae60,
        description: 'Throw acid jar at cursor, instant damage + DoT'
    },
    toxic_puddle: {
        key: 'toxic_puddle',
        name: 'Toxic Puddle',
        nameRu: 'Токсичная Лужа',
        nameDe: 'Toxische Pfütze',
        slot: 'W',
        corruptionCost: 15,
        cooldown: 6.0,
        damagePerSec: 3,
        duration: 4.0,
        radius: 70,
        range: 200,
        slowPercent: 40,
        color: 0x27ae60,
        description: 'Throw puddle at cursor, slows enemies and deals DoT'
    },
    burrow: {
        key: 'burrow',
        name: 'Burrow',
        nameRu: 'Зарыться',
        nameDe: 'Eingraben',
        slot: 'E',
        corruptionCost: 0,
        cooldown: 12.0,
        duration: 2.0,
        healPercent: 0.30,
        color: 0x8B4513,
        description: 'Burrow into ground for 2s, invulnerable, heal 30% HP'
    },
    soul_strike: {
        key: 'soul_strike',
        name: 'Soul Strike',
        nameRu: 'Удар Души',
        nameDe: 'Seelenschlag',
        slot: 'Q',
        corruptionCost: 10,
        cooldown: 2.5,
        damage: 0,
        healOnHit: 0.5,
        speed: 350,
        range: 400,
        healZoneRadius: 80,
        healZoneDuration: 3.0,
        healZoneHealPerSec: 0.04,
        color: 0xf1c40f,
        description: 'Fires holy bolt, heals on hit, creates heal zone at max range'
    },
    holy_shield: {
        key: 'holy_shield',
        name: 'Holy Shield',
        nameRu: 'Святой Щит',
        nameDe: 'Heiliger Schild',
        slot: 'W',
        corruptionCost: 15,
        cooldown: 8.0,
        absorption: 60,
        duration: 5.0,
        color: 0xf1c40f,
        description: 'Place a shield on cursor target, absorbs damage'
    },
    holy_nova: {
        key: 'holy_nova',
        name: 'Holy Nova',
        nameRu: 'Святой Взрыв',
        nameDe: 'Heilige Nova',
        slot: 'E',
        corruptionCost: 0,
        cooldown: 10.0,
        healPercent: 0.25,
        corruptionReduce: 30,
        radius: 120,
        color: 0xf1c40f,
        description: 'Burst of holy energy, heals and reduces corruption'
    },
    purify: {
        key: 'purify',
        name: 'Purify',
        nameRu: 'Очищение',
        nameDe: 'Reinigung',
        slot: 'E',
        corruptionCost: 0,
        cooldown: 12.0,
        corruptionReduce: 40,
        healPercent: 0.15,
        color: 0xf1c40f,
        description: 'Removes 40 corruption and heals 15% maxHP'
    },
    iron_skin: {
        key: 'iron_skin',
        name: 'Iron Skin',
        nameRu: 'Железная Кожа',
        nameDe: 'Eisenhaut',
        slot: 'W',
        corruptionCost: 18,
        cooldown: 7.0,
        absorption: 40,
        damageReduction: 0.30,
        duration: 5.0,
        color: 0x95a5a6,
        description: 'Reduces incoming damage by 30% for 5 seconds'
    },
    healing_potion: {
        key: 'healing_potion',
        name: 'Healing Potion',
        nameRu: 'Зелье Исцеления',
        nameDe: 'Heiltrank',
        slot: 'E',
        corruptionCost: 20,
        cooldown: 8.0,
        healPercent: 0.35,
        color: 0xe67e22,
        description: 'Restores 35% of max HP'
    },
    meteor: {
        key: 'meteor',
        name: 'Meteor',
        nameRu: 'Метеор',
        nameDe: 'Meteor',
        slot: 'R',
        corruptionCost: 35,
        cooldown: 18.0,
        damage: 150,
        dot: 10,
        dotDuration: 4.0,
        radius: 130,
        range: 350,
        color: 0xe74c3c,
        description: 'Calls down a devastating meteor dealing massive AoE fire damage'
    },
    chemical_cloud: {
        key: 'chemical_cloud',
        name: 'Chemical Cloud',
        nameRu: 'Химическое Облако',
        nameDe: 'Chemische Wolke',
        slot: 'R',
        corruptionCost: 30,
        cooldown: 22.0,
        damagePerSec: 12,
        duration: 6.0,
        radius: 110,
        range: 250,
        armorReduction: 25,
        slowPercent: 40,
        color: 0x27ae60,
        description: 'Creates a massive toxic cloud dealing heavy DoT and reducing armor'
    },
    divine_blessing: {
        key: 'divine_blessing',
        name: 'Divine Blessing',
        nameRu: 'Благословение',
        nameDe: 'Gesegnet',
        slot: 'R',
        corruptionCost: 0,
        cooldown: 25.0,
        healPercent: 0.50,
        buffDuration: 8.0,
        damageBuff: 25,
        defenseBuff: 20,
        color: 0xf1c40f,
        description: 'Heals 50% HP and grants +25% DMG, +20% DEF for 8s'
    },

    // === NEW SPELLS: Sage ===
    chain_lightning: {
        key: 'chain_lightning',
        name: 'Chain Lightning',
        nameRu: 'Цепная Молния',
        nameDe: 'Kettenblitz',
        slot: 'Q',
        corruptionCost: 15,
        cooldown: 3.0,
        damage: 35,
        chainCount: 3,
        chainRange: 150,
        speed: 500,
        range: 350,
        color: 0x3498db,
        unlockLevel: 5,
        description: 'Lightning bolt that chains to 3 nearby enemies'
    },
    arcane_burst: {
        key: 'arcane_burst',
        name: 'Arcane Burst',
        nameRu: 'Тайный Взрыв',
        nameDe: 'Arkaner Ausbruch',
        slot: 'W',
        corruptionCost: 18,
        cooldown: 6.0,
        damage: 80,
        radius: 100,
        range: 200,
        color: 0x9b59b6,
        unlockLevel: 10,
        description: 'AoE arcane explosion around player'
    },
    time_warp: {
        key: 'time_warp',
        name: 'Time Warp',
        nameRu: 'Искажение Времени',
        nameDe: 'Zeitverzerrung',
        slot: 'E',
        corruptionCost: 25,
        cooldown: 15.0,
        duration: 3.0,
        slowPercent: 50,
        radius: 150,
        color: 0x9b59b6,
        unlockLevel: 15,
        description: 'Slows all enemies in area by 50% for 3s'
    },
    nova_blast: {
        key: 'nova_blast',
        name: 'Nova Blast',
        nameRu: 'Взрыв Новы',
        nameDe: 'Nova-Ausbruch',
        slot: 'R',
        corruptionCost: 40,
        cooldown: 20.0,
        damage: 200,
        radius: 180,
        range: 300,
        color: 0xe74c3c,
        unlockLevel: 20,
        description: 'Massive arcane explosion dealing huge AoE damage'
    },

    // === NEW SPELLS: Alchemist ===
    poison_cloud: {
        key: 'poison_cloud',
        name: 'Poison Cloud',
        nameRu: 'Ядовитое Облако',
        nameDe: 'Giftwolke',
        slot: 'Q',
        corruptionCost: 14,
        cooldown: 2.5,
        damagePerSec: 6,
        duration: 4.0,
        radius: 80,
        range: 250,
        slowPercent: 20,
        color: 0x27ae60,
        unlockLevel: 5,
        description: 'Creates a poison cloud dealing DoT and slowing enemies'
    },
    transmute: {
        key: 'transmute',
        name: 'Transmute',
        nameRu: 'Трансмутация',
        nameDe: 'Transmutation',
        slot: 'W',
        corruptionCost: 10,
        cooldown: 8.0,
        healPercent: 0.25,
        damageBuff: 15,
        buffDuration: 5.0,
        color: 0xe67e22,
        unlockLevel: 10,
        description: 'Converts corruption into power: heal 25% HP, +15% DMG for 5s'
    },
    summon_golem: {
        key: 'summon_golem',
        name: 'Summon Golem',
        nameRu: 'Призыв Голема',
        nameDe: 'Golem beschwören',
        slot: 'E',
        corruptionCost: 30,
        cooldown: 20.0,
        duration: 10.0,
        summonHp: 200,
        summonDamage: 15,
        color: 0x95a5a6,
        unlockLevel: 15,
        description: 'Summons a stone golem that fights for 10s'
    },
    philosopher_stone: {
        key: 'philosopher_stone',
        name: 'Philosopher Stone',
        nameRu: 'Камень Философа',
        nameDe: 'Stein der Weisen',
        slot: 'R',
        corruptionCost: 0,
        cooldown: 30.0,
        duration: 10.0,
        healPercent: 0.30,
        damageBuff: 20,
        defenseBuff: 15,
        color: 0xf1c40f,
        unlockLevel: 20,
        description: 'Ultimate transmutation: heal 30%, +20% DMG, +15% DEF for 10s'
    },

    // === NEW SPELLS: Angel ===
    smite: {
        key: 'smite',
        name: 'Smite',
        nameRu: 'Кара',
        nameDe: 'Bestrafung',
        slot: 'Q',
        corruptionCost: 12,
        cooldown: 2.0,
        damage: 60,
        speed: 450,
        range: 400,
        color: 0xf1c40f,
        unlockLevel: 5,
        description: 'Fires a bolt of divine energy dealing holy damage'
    },
    divine_shield: {
        key: 'divine_shield',
        name: 'Divine Shield',
        nameRu: 'Божественный Щит',
        nameDe: 'Göttlicher Schild',
        slot: 'W',
        corruptionCost: 18,
        cooldown: 10.0,
        absorption: 80,
        duration: 6.0,
        reflectPercent: 15,
        color: 0xf1c40f,
        unlockLevel: 10,
        description: 'Shield that absorbs damage and reflects 15% back'
    },
    resurrection: {
        key: 'resurrection',
        name: 'Resurrection',
        nameRu: 'Воскрешение',
        nameDe: 'Auferstehung',
        slot: 'E',
        corruptionCost: 0,
        cooldown: 60.0,
        healPercent: 1.0,
        color: 0xf1c40f,
        unlockLevel: 15,
        description: 'Fully restores HP. Once per zone.'
    },
    archangel_form: {
        key: 'archangel_form',
        name: 'Archangel Form',
        nameRu: 'Форма Архангела',
        nameDe: 'Erzengel-Form',
        slot: 'R',
        corruptionCost: 0,
        cooldown: 45.0,
        duration: 12.0,
        healPercent: 0.50,
        damageBuff: 40,
        defenseBuff: 30,
        speedBuff: 20,
        color: 0xf1c40f,
        unlockLevel: 20,
        description: 'Transform into archangel: +40% DMG, +30% DEF, +20% SPD for 12s'
    }
};
