export const SPELLS = {
    fireball: {
        key: 'fireball',
        name: 'Fireball',
        nameRu: 'Огненный Шар',
        nameDe: 'Feuerball',
        slot: 'Q',
        corruptionCost: 12,
        cooldown: 1.5,
        damage: 55,
        speed: 400,
        range: 450,
        color: 0xe74c3c,
        description: 'Hurls a blazing fireball dealing spell damage'
    },
    shield: {
        key: 'shield',
        name: 'Arcane Shield',
        nameRu: 'Щит',
        nameDe: 'Arkaner Schild',
        slot: 'W',
        corruptionCost: 20,
        cooldown: 8.0,
        absorption: 50,
        duration: 5.0,
        color: 0x3498db,
        description: 'Absorbs damage for 5 seconds'
    },
    heal: {
        key: 'heal',
        name: 'Heal',
        nameRu: 'Исцеление',
        nameDe: 'Heilung',
        slot: 'E',
        corruptionCost: 20,
        cooldown: 8.0,
        healPercent: 0.40,
        color: 0x2ecc71,
        description: 'Restores 40% of max HP with holy light'
    },
    acid_flask: {
        key: 'acid_flask',
        name: 'Acid Flask',
        nameRu: 'Кислотная Бутылка',
        nameDe: 'Säureflasche',
        slot: 'Q',
        corruptionCost: 12,
        cooldown: 2.0,
        damage: 45,
        range: 250,
        radius: 50,
        dot: 8,
        dotDuration: 2.0,
        color: 0x27ae60,
        description: 'Throw acid jar at cursor, instant damage + DoT'
    },
    toxic_puddle: {
        key: 'toxic_puddle',
        name: 'Toxic Puddle',
        nameRu: 'Токсичная Лужа',
        nameDe: 'Toxische Pfütze',
        slot: 'W',
        corruptionCost: 15,
        cooldown: 6.0,
        damagePerSec: 3,
        duration: 4.0,
        radius: 70,
        range: 200,
        slowPercent: 40,
        color: 0x27ae60,
        description: 'Throw puddle at cursor, slows enemies and deals DoT'
    },
    burrow: {
        key: 'burrow',
        name: 'Burrow',
        nameRu: 'Зарыться',
        nameDe: 'Eingraben',
        slot: 'E',
        corruptionCost: 0,
        cooldown: 12.0,
        duration: 2.0,
        healPercent: 0.30,
        color: 0x8B4513,
        description: 'Burrow into ground for 2s, invulnerable, heal 30% HP'
    },
    soul_strike: {
        key: 'soul_strike',
        name: 'Soul Strike',
        nameRu: 'Удар Души',
        nameDe: 'Seelenschlag',
        slot: 'Q',
        corruptionCost: 10,
        cooldown: 2.5,
        damage: 0,
        healOnHit: 0.5,
        speed: 350,
        range: 400,
        healZoneRadius: 80,
        healZoneDuration: 3.0,
        healZoneHealPerSec: 0.04,
        color: 0xf1c40f,
        description: 'Fires holy bolt, heals on hit, creates heal zone at max range'
    },
    holy_shield: {
        key: 'holy_shield',
        name: 'Holy Shield',
        nameRu: 'Святой Щит',
        nameDe: 'Heiliger Schild',
        slot: 'W',
        corruptionCost: 15,
        cooldown: 8.0,
        absorption: 60,
        duration: 5.0,
        color: 0xf1c40f,
        description: 'Place a shield on cursor target, absorbs damage'
    },
    holy_nova: {
        key: 'holy_nova',
        name: 'Holy Nova',
        nameRu: 'Святой Взрыв',
        nameDe: 'Heilige Nova',
        slot: 'E',
        corruptionCost: 0,
        cooldown: 10.0,
        healPercent: 0.25,
        corruptionReduce: 30,
        radius: 120,
        color: 0xf1c40f,
        description: 'Burst of holy energy, heals and reduces corruption'
    },
    purify: {
        key: 'purify',
        name: 'Purify',
        nameRu: 'Очищение',
        nameDe: 'Reinigung',
        slot: 'E',
        corruptionCost: 0,
        cooldown: 12.0,
        corruptionReduce: 40,
        healPercent: 0.15,
        color: 0xf1c40f,
        description: 'Removes 40 corruption and heals 15% maxHP'
    },
    iron_skin: {
        key: 'iron_skin',
        name: 'Iron Skin',
        nameRu: 'Железная Кожа',
        nameDe: 'Eisenhaut',
        slot: 'W',
        corruptionCost: 18,
        cooldown: 7.0,
        absorption: 40,
        damageReduction: 0.30,
        duration: 5.0,
        color: 0x95a5a6,
        description: 'Reduces incoming damage by 30% for 5 seconds'
    },
    healing_potion: {
        key: 'healing_potion',
        name: 'Healing Potion',
        nameRu: 'Зелье Исцеления',
        nameDe: 'Heiltrank',
        slot: 'E',
        corruptionCost: 20,
        cooldown: 8.0,
        healPercent: 0.35,
        color: 0xe67e22,
        description: 'Restores 35% of max HP'
    },
    meteor: {
        key: 'meteor',
        name: 'Meteor',
        nameRu: 'Метеор',
        nameDe: 'Meteor',
        slot: 'R',
        corruptionCost: 35,
        cooldown: 18.0,
        damage: 150,
        dot: 10,
        dotDuration: 4.0,
        radius: 130,
        range: 350,
        color: 0xe74c3c,
        description: 'Calls down a devastating meteor dealing massive AoE fire damage'
    },
    chemical_cloud: {
        key: 'chemical_cloud',
        name: 'Chemical Cloud',
        nameRu: 'Химическое Облако',
        nameDe: 'Chemische Wolke',
        slot: 'R',
        corruptionCost: 30,
        cooldown: 22.0,
        damagePerSec: 12,
        duration: 6.0,
        radius: 110,
        range: 250,
        armorReduction: 25,
        slowPercent: 40,
        color: 0x27ae60,
        description: 'Creates a massive toxic cloud dealing heavy DoT and reducing armor'
    },
    divine_blessing: {
        key: 'divine_blessing',
        name: 'Divine Blessing',
        nameRu: 'Благословение',
        nameDe: 'Gesegnet',
        slot: 'R',
        corruptionCost: 0,
        cooldown: 25.0,
        healPercent: 0.50,
        buffDuration: 8.0,
        damageBuff: 25,
        defenseBuff: 20,
        color: 0xf1c40f,
        description: 'Heals 50% HP and grants +25% DMG, +20% DEF for 8s'
    }
};
